language: node_js
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - prettier "*.{js,md}" "app/*.{js,css}" --list-different
  - npm run build
after_script: greenkeeper-lockfile-upload
deploy:
  provider: surge
  project: ./dist/
  domain: postcss-repl.surge.sh
  skip_cleanup: true
