module.exports = {
  /* AUTO-GENERATED; DO NOT EDIT */

  'postcss-simple-vars': {
    name: 'postcss-simple-vars',
    plugin: require('postcss-simple-vars'),
    pkgName: 'postcss-simple-vars',
    pkgUrl: 'https://www.npmjs.com/package/postcss-simple-vars',
    config: null,
    url: 'https://github.com/postcss/postcss-simple-vars',
    description: `Supports for Sass-style variables.`,
    tags: ['extensions', 'sass'],
    author: 'postcss',
    stars: 262,
  },

  'postcss-advanced-variables': {
    name: 'postcss-advanced-variables',
    plugin: require('postcss-advanced-variables')({ disable: ['@import'] }),
    pkgName: 'postcss-advanced-variables',
    pkgUrl: 'https://www.npmjs.com/package/postcss-advanced-variables',
    config: { disable: ['@import'] },
    url: 'https://github.com/jonathantneal/postcss-advanced-variables',
    description: `lets you use Sass-like variables, conditionals, and iterators in CSS.`,
    tags: ['extensions', 'sass'],
    author: 'jonathantneal',
    stars: 35,
  },

  'postcss-mixins': {
    name: 'postcss-mixins',
    plugin: require('postcss-mixins'),
    pkgName: 'postcss-mixins',
    pkgUrl: 'https://www.npmjs.com/package/postcss-mixins',
    config: null,
    url: 'https://github.com/postcss/postcss-mixins',
    description: `Enables mixins more powerful than Sass', defined within stylesheets or in JS.`,
    tags: ['extensions', 'sass'],
    author: 'postcss',
    stars: 257,
  },

  'postcss-nesting': {
    name: 'postcss-nesting',
    plugin: require('postcss-nesting'),
    pkgName: 'postcss-nesting',
    pkgUrl: 'https://www.npmjs.com/package/postcss-nesting',
    config: null,
    url: 'https://github.com/jonathantneal/postcss-nesting',
    description: `Nest one style rule inside another, following the CSS Nesting Module Level 3 specification.`,
    tags: ['extensions', 'future', 'media-queries'],
    author: 'jonathantneal',
    stars: 157,
  },

  'postcss-nested': {
    name: 'postcss-nested',
    plugin: require('postcss-nested'),
    pkgName: 'postcss-nested',
    pkgUrl: 'https://www.npmjs.com/package/postcss-nested',
    config: null,
    url: 'https://github.com/postcss/postcss-nested',
    description: `Unwraps nested rules.`,
    tags: ['extensions', 'sass'],
    author: 'postcss',
    stars: 414,
  },

  short: {
    name: 'short',
    plugin: require('postcss-short'),
    pkgName: 'postcss-short',
    pkgUrl: 'https://www.npmjs.com/package/postcss-short',
    config: null,
    url: 'https://github.com/jonathantneal/postcss-short',
    description: `Adds and extends numerous shorthand properties.`,
    tags: ['pack'],
    author: 'jonathantneal',
    stars: 138,
  },

  rucksack: {
    name: 'rucksack',
    plugin: require('rucksack-css'),
    pkgName: 'rucksack-css',
    pkgUrl: 'https://www.npmjs.com/package/rucksack-css',
    config: null,
    url: 'https://github.com/simplaio/rucksack',
    description: `Plugin pack to speeds up CSS development with new features and shortcuts.`,
    tags: ['pack', 'future'],
    author: 'simplaio',
    stars: 1742,
  },

  lost: {
    name: 'lost',
    plugin: require('lost'),
    pkgName: 'lost',
    pkgUrl: 'https://www.npmjs.com/package/lost',
    config: null,
    url: 'https://github.com/peterramsing/lost',
    description: `Feature-rich calc() grid system.`,
    tags: ['grids'],
    author: 'corysimmons',
    stars: 3972,
  },

  'postcss-cssnext': {
    name: 'postcss-cssnext',
    plugin: require('postcss-cssnext')({ warnForDuplicates: false }),
    pkgName: 'postcss-cssnext',
    pkgUrl: 'https://www.npmjs.com/package/postcss-cssnext',
    config: { warnForDuplicates: false },
    url: 'https://github.com/MoOx/postcss-cssnext',
    description: `Plugin pack that allows you to use future CSS features today.`,
    tags: ['pack', 'future'],
    author: 'cssnext',
    stars: 4938,
  },

  'postcss-ordered-values': {
    name: 'postcss-ordered-values',
    plugin: require('postcss-ordered-values'),
    pkgName: 'postcss-ordered-values',
    pkgUrl: 'https://www.npmjs.com/package/postcss-ordered-values',
    config: null,
    url: 'https://github.com/ben-eb/postcss-ordered-values',
    description: ` that ensures a consistent ordering of values.`,
    tags: ['optimizations'],
    author: 'ben-eb',
    stars: 37,
  },

  'postcss-calc': {
    name: 'postcss-calc',
    plugin: require('postcss-calc'),
    pkgName: 'postcss-calc',
    pkgUrl: 'https://www.npmjs.com/package/postcss-calc',
    config: null,
    url: 'https://github.com/postcss/postcss-calc',
    description: `Reduces calc() to values (when expressions involve the same units).`,
    tags: ['optimizations'],
    author: 'postcss',
    stars: 111,
  },

  'postcss-flexbugs-fixes': {
    name: 'postcss-flexbugs-fixes',
    plugin: require('postcss-flexbugs-fixes'),
    pkgName: 'postcss-flexbugs-fixes',
    pkgUrl: 'https://www.npmjs.com/package/postcss-flexbugs-fixes',
    config: null,
    url: 'https://github.com/luisrudge/postcss-flexbugs-fixes',
    description: `fixes to some of known flexbox bugs`,
    tags: ['analysis'],
    author: 'luisrudge',
    stars: 442,
  },

  autoprefixer: {
    name: 'autoprefixer',
    plugin: require('autoprefixer'),
    pkgName: 'autoprefixer',
    pkgUrl: 'https://www.npmjs.com/package/autoprefixer',
    config: null,
    url: 'https://github.com/postcss/autoprefixer',
    description: `Adds vendor prefixes for you, using data from Can I Use.`,
    tags: ['fallbacks'],
    author: 'postcss',
    stars: 14462,
  },

  cssnano: {
    name: 'cssnano',
    plugin: require('cssnano-browser'),
    pkgName: 'cssnano-browser',
    pkgUrl: 'https://www.npmjs.com/package/cssnano-browser',
    config: null,
    url: 'https://github.com/ben-eb/cssnano',
    description: `Plugin pack that optimizes CSS size for use in production.`,
    tags: ['pack', 'optimizations'],
    author: 'ben-eb',
    stars: 2178,
  },

  /* END AUTO-GENERATED */
};
